# Generated by Django 3.2.25 on 2024-05-22 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=700)),
                ('Product_Type', models.CharField(choices=[('Phone', 'Phone'), ('Arduino', 'Arduino'), ('Computer', 'Computer'), ('Laptop', 'Laptop'), ('Watch', 'Watch'), ('Camera', 'Camera'), ('Drone', 'Drone'), ('Chargers', 'Chargers'), ('Microphones', 'Microphones'), ('Batteries', 'Batteries'), ('Cable and Adapters', 'Cable and Adapters'), ('Television', 'Television')], max_length=200, null=True)),
                ('Product_Description', models.CharField(max_length=500)),
                ('Specification', models.CharField(max_length=500)),
                ('Selling_Cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Actual_Cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Image1', models.ImageField(upload_to='home/')),
                ('Image2', models.ImageField(upload_to='home/')),
                ('Image3', models.ImageField(upload_to='home/')),
                ('Image4', models.ImageField(upload_to='home/')),
                ('Image5', models.ImageField(upload_to='home/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commentproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('Title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
