# Generated by Django 3.2.25 on 2024-05-31 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_payment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Details',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Features',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='Specification',
            field=models.CharField(max_length=1000),
        ),
    ]
