# Generated by Django 4.2.3 on 2023-12-07 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='username')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('hide_email', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaNumber',
            fields=[
                ('Ca_Number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamNumber',
            fields=[
                ('Exam_Number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='username')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('hide_email', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Collage', models.CharField(choices=[('coste', 'coste'), ('coict', 'coict')], max_length=40)),
                ('Department', models.CharField(choices=[('computer engineering', 'computer engineering'), ('computer science', 'computer science'), ('civil engineering', 'civil engineering')], max_length=40)),
                ('Level', models.CharField(choices=[('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Phd', 'Phd')], max_length=40)),
                ('course', models.CharField(choices=[('computer engineering', 'computer engineering'), ('civil engineering', 'civil engineering'), ('biomedical', 'biomedical'), ('electrical engineering', 'electrical engineering'), ('computer science', 'computer science')], max_length=40)),
                ('years', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=40)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentContactinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_type', models.CharField(choices=[('Student', 'Student')], max_length=40)),
                ('First_Name', models.CharField(max_length=100)),
                ('Middle_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Collage', models.CharField(choices=[('coste', 'coste'), ('coict', 'coict')], max_length=40)),
                ('Department', models.CharField(choices=[('computer engineering', 'computer engineering'), ('computer science', 'computer science'), ('civil engineering', 'civil engineering')], max_length=40)),
                ('Level', models.CharField(choices=[('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Phd', 'Phd')], max_length=40)),
                ('course', models.CharField(choices=[('computer engineering', 'computer engineering'), ('civil engineering', 'civil engineering'), ('biomedical', 'biomedical'), ('electrical engineering', 'electrical engineering'), ('computer science', 'computer science')], max_length=40)),
                ('years', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=40)),
                ('Region', models.CharField(choices=[('Arusha', 'Arusha'), ('Dodoma', 'Dodoma'), ('Mwanza', 'Mwanza'), ('Iringa', 'Iringa'), ('Tabora', 'Tabora')], max_length=40)),
                ('Phone', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=100)),
                ('Course_Code', models.CharField(max_length=100)),
                ('Result', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('Exam_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sims.examnumber')),
            ],
        ),
        migrations.CreateModel(
            name='CaResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=100)),
                ('Course_Code', models.CharField(max_length=100)),
                ('Assignment', models.CharField(max_length=100)),
                ('Quiz', models.CharField(max_length=100)),
                ('Test_1', models.CharField(max_length=100)),
                ('Test_2', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('Ca_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sims.canumber')),
            ],
        ),
    ]
