# Generated by Django 4.2.3 on 2023-12-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caresult',
            name='Assignment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caresult',
            name='Quiz',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caresult',
            name='Test_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caresult',
            name='Test_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finalresult',
            name='Result',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
