# Generated by Django 4.2.3 on 2023-12-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0003_alter_caresult_course_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caresult',
            name='Course_Code',
            field=models.CharField(choices=[('COB2211', 'COB2211'), ('COB2212', 'COB2212')], max_length=40),
        ),
        migrations.AlterField(
            model_name='caresult',
            name='Course_Name',
            field=models.CharField(choices=[('computer gearphics', 'computer gearphics'), ('basic electricity', 'basic electricity'), ('software engineering', 'software engineering')], max_length=40),
        ),
    ]
