# Generated by Django 4.2.3 on 2023-12-08 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0006_alter_caresult_assignment_alter_caresult_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canumber',
            name='Academic_Year',
            field=models.CharField(choices=[('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026'), ('2026/2027', '2026/2027'), ('2027/2028', '2027/2028'), ('2029/2030', '2029/2030')], default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
