# Generated by Django 4.2.3 on 2023-12-08 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0007_canumber_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='canumber',
            name='SystemExitemister',
            field=models.CharField(choices=[('1', '1'), ('1', '1')], default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caresult',
            name='Semister',
            field=models.CharField(choices=[('1', '1'), ('1', '1')], default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
