# Generated by Django 4.2.3 on 2023-12-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0008_canumber_systemexitemister_caresult_semister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canumber',
            name='SystemExitemister',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], max_length=40),
        ),
        migrations.AlterField(
            model_name='caresult',
            name='Semister',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], max_length=40),
        ),
    ]
