# Generated by Django 4.2.3 on 2023-12-08 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0009_alter_canumber_systemexitemister_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canumber',
            old_name='SystemExitemister',
            new_name='Semister',
        ),
    ]
