# Generated by Django 4.2.3 on 2023-12-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0010_rename_systemexitemister_canumber_semister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='course',
            field=models.CharField(choices=[('computer engineering', 'computer engineering'), ('electrical engineering', 'electrical engineering'), ('mechanical engineering', 'mechanical engineering')], max_length=40),
        ),
    ]
