# Generated by Django 4.2.3 on 2023-12-14 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0012_canumber_course_examnumber_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalresult',
            name='Academic_Year',
            field=models.CharField(choices=[('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026'), ('2026/2027', '2026/2027'), ('2027/2028', '2027/2028'), ('2029/2030', '2029/2030')], default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finalresult',
            name='Semister',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caresult',
            name='Course_Name',
            field=models.CharField(choices=[('Computer Engineering', 'Computer Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering')], max_length=40),
        ),
        migrations.AlterField(
            model_name='finalresult',
            name='Course_Code',
            field=models.CharField(choices=[('COB2211', 'COB2211'), ('COB2212', 'COB2212')], max_length=40),
        ),
        migrations.AlterField(
            model_name='finalresult',
            name='Course_Name',
            field=models.CharField(choices=[('Computer Engineering', 'Computer Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering')], max_length=40),
        ),
    ]
