# Generated by Django 3.2.25 on 2024-05-22 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0016_finalresult_ca_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canumber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sims.mystaff'),
        ),
        migrations.AlterField(
            model_name='examnumber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sims.mystaff'),
        ),
        migrations.AlterField(
            model_name='staffcontactinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sims.mystaff'),
        ),
        migrations.AlterField(
            model_name='studentcontactinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sims.mystaff'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sims.mystaff'),
        ),
    ]
